{
 "title": "OTel Hostmetrics Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Network Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_system_network_connections",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Network IO Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(default_system_network_io_bytes_total[5m])",
     "legendFormat": "{{device}} {{direction}}"
    }
   ]
  },
  {
   "title": "CPU Cycles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(state) (rate(default_system_cpu_time_seconds_total[5m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "System Uptime (Metric in s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "default_system_uptime_seconds" }
   ]
  },
  {
   "title": "Network Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_system_network_errors_total",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Network Packages Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(direction) (default_system_network_packets_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Averages",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "default_system_cpu_load_average_1m",
     "legendFormat": "1m"
    },
    {
     "expr": "default_system_cpu_load_average_5m",
     "legendFormat": "5m"
    },
    {
     "expr": "default_system_cpu_load_average_15m",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Memory Usage (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "default_system_memory_usage_bytes",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}